// GENERATED by package:ffigen from include/aa.h. Do not edit by hand;
// run `dart run ffigen` to regenerate after the C header changes.
// ignore_for_file: always_specify_types, camel_case_types, non_constant_identifier_names, unused_element, unused_field, doc_directive_unknown, no_leading_underscores_for_library_prefixes

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Low-level FFI bindings for the ZeroDev AA C API (include/aa.h).
class AaBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  AaBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  AaBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Create a Kernel smart account.
  ///
  /// `address` may be NULL, in which case the sender address is derived
  /// counterfactually via CREATE2 from `(owner, index, version)` — the standard
  /// flow. When non-NULL, it pins the account's sender to that address.
  ///
  /// This is the migration path for accounts whose original CREATE2 inputs
  /// (older kernel version, factory salt) this SDK cannot reproduce — post-
  /// upgrade the on-chain address is fixed but `(signer, version, index)` in
  /// the new SDK derives a different one. The caller passes the correct
  /// address; the SDK has nothing to cross-check against.
  ///
  /// Pinning affects the sender only. Factory init_code is still emitted on
  /// the first UserOp exactly as it would be for a counterfactually-derived
  /// account (governed by the EntryPoint nonce). Callers pinning an
  /// already-deployed account whose EntryPoint nonce is still 0 (rare —
  /// funded but never used) should drop the factory bytes via the low-level
  /// UserOp API.
  aa_status aa_account_create(
    ffi.Pointer<aa_context_t> ctx,
    ffi.Pointer<aa_signer_t> signer,
    aa_kernel_version version,
    int index,
    ffi.Pointer<ffi.Uint8> address,
    ffi.Pointer<ffi.Pointer<aa_account_t>> out,
  ) {
    return aa_status.fromValue(_aa_account_create(
      ctx,
      signer,
      version.value,
      index,
      address,
      out,
    ));
  }

  late final _aa_account_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<aa_context_t>,
              ffi.Pointer<aa_signer_t>,
              ffi.UnsignedInt,
              ffi.Uint32,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Pointer<aa_account_t>>)>>('aa_account_create');
  late final _aa_account_create = _aa_account_createPtr.asFunction<
      int Function(
          ffi.Pointer<aa_context_t>,
          ffi.Pointer<aa_signer_t>,
          int,
          int,
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Pointer<aa_account_t>>)>();

  aa_status aa_account_destroy(
    ffi.Pointer<aa_account_t> account,
  ) {
    return aa_status.fromValue(_aa_account_destroy(
      account,
    ));
  }

  late final _aa_account_destroyPtr = _lookup<
          ffi
          .NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<aa_account_t>)>>(
      'aa_account_destroy');
  late final _aa_account_destroy = _aa_account_destroyPtr
      .asFunction<int Function(ffi.Pointer<aa_account_t>)>();

  aa_status aa_account_get_address(
    ffi.Pointer<aa_account_t> account,
    ffi.Pointer<ffi.Uint8> addr_out,
  ) {
    return aa_status.fromValue(_aa_account_get_address(
      account,
      addr_out,
    ));
  }

  late final _aa_account_get_addressPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<aa_account_t>,
              ffi.Pointer<ffi.Uint8>)>>('aa_account_get_address');
  late final _aa_account_get_address = _aa_account_get_addressPtr.asFunction<
      int Function(ffi.Pointer<aa_account_t>, ffi.Pointer<ffi.Uint8>)>();

  /// Allocate `size` bytes via libc `malloc`. Returns NULL on failure or
  /// when `size` is 0. The matching free is `aa_free`.
  ///
  /// Audit F-02: prefer this over the host's native allocator when handing
  /// buffers back to the SDK across FFI (HTTP responses, paymaster_data).
  /// It guarantees the SDK can safely call libc `free` on the pointer on
  /// every platform, since `aa_alloc` IS libc malloc.
  ffi.Pointer<ffi.Void> aa_alloc(
    int size,
  ) {
    return _aa_alloc(
      size,
    );
  }

  late final _aa_allocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size)>>(
          'aa_alloc');
  late final _aa_alloc =
      _aa_allocPtr.asFunction<ffi.Pointer<ffi.Void> Function(int)>();

  /// ---- Context (holds RPC URLs, chain config) ----
  aa_status aa_context_create(
    ffi.Pointer<ffi.Char> project_id,
    ffi.Pointer<ffi.Char> rpc_url,
    ffi.Pointer<ffi.Char> bundler_url,
    int chain_id,
    ffi.Pointer<ffi.Pointer<aa_context_t>> out,
  ) {
    return aa_status.fromValue(_aa_context_create(
      project_id,
      rpc_url,
      bundler_url,
      chain_id,
      out,
    ));
  }

  late final _aa_context_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Uint64,
              ffi.Pointer<ffi.Pointer<aa_context_t>>)>>('aa_context_create');
  late final _aa_context_create = _aa_context_createPtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Pointer<aa_context_t>>)>();

  aa_status aa_context_destroy(
    ffi.Pointer<aa_context_t> ctx,
  ) {
    return aa_status.fromValue(_aa_context_destroy(
      ctx,
    ));
  }

  late final _aa_context_destroyPtr = _lookup<
          ffi
          .NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<aa_context_t>)>>(
      'aa_context_destroy');
  late final _aa_context_destroy = _aa_context_destroyPtr
      .asFunction<int Function(ffi.Pointer<aa_context_t>)>();

  /// Create an EIP-7702 account. The account's address is the signer's EOA
  /// address; there is no CREATE2, no init code, and no index parameter. On the
  /// first UserOperation the SDK signs an authorization tuple (chainId, Kernel
  /// implementation for `version`, EOA nonce) and attaches it via the
  /// `eip7702Auth` field. Today only KERNEL_V3_3 supports EIP-7702.
  aa_status aa_context_new_account_7702(
    ffi.Pointer<aa_context_t> ctx,
    ffi.Pointer<aa_signer_t> signer,
    aa_kernel_version version,
    ffi.Pointer<ffi.Pointer<aa_account_t>> out,
  ) {
    return aa_status.fromValue(_aa_context_new_account_7702(
      ctx,
      signer,
      version.value,
      out,
    ));
  }

  late final _aa_context_new_account_7702Ptr = _lookup<
          ffi.NativeFunction<
              ffi.UnsignedInt Function(
                  ffi.Pointer<aa_context_t>,
                  ffi.Pointer<aa_signer_t>,
                  ffi.UnsignedInt,
                  ffi.Pointer<ffi.Pointer<aa_account_t>>)>>(
      'aa_context_new_account_7702');
  late final _aa_context_new_account_7702 =
      _aa_context_new_account_7702Ptr.asFunction<
          int Function(ffi.Pointer<aa_context_t>, ffi.Pointer<aa_signer_t>, int,
              ffi.Pointer<ffi.Pointer<aa_account_t>>)>();

  aa_status aa_context_set_gas_middleware(
    ffi.Pointer<aa_context_t> ctx,
    aa_gas_price_fn middleware,
  ) {
    return aa_status.fromValue(_aa_context_set_gas_middleware(
      ctx,
      middleware,
    ));
  }

  late final _aa_context_set_gas_middlewarePtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<aa_context_t>,
              aa_gas_price_fn)>>('aa_context_set_gas_middleware');
  late final _aa_context_set_gas_middleware = _aa_context_set_gas_middlewarePtr
      .asFunction<int Function(ffi.Pointer<aa_context_t>, aa_gas_price_fn)>();

  aa_status aa_context_set_http_free_fn(
    ffi.Pointer<aa_context_t> ctx,
    aa_http_free_fn free_fn,
  ) {
    return aa_status.fromValue(_aa_context_set_http_free_fn(
      ctx,
      free_fn,
    ));
  }

  late final _aa_context_set_http_free_fnPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<aa_context_t>,
              aa_http_free_fn)>>('aa_context_set_http_free_fn');
  late final _aa_context_set_http_free_fn = _aa_context_set_http_free_fnPtr
      .asFunction<int Function(ffi.Pointer<aa_context_t>, aa_http_free_fn)>();

  aa_status aa_context_set_http_transport(
    ffi.Pointer<aa_context_t> ctx,
    aa_http_fn transport,
    ffi.Pointer<ffi.Void> transport_ctx,
  ) {
    return aa_status.fromValue(_aa_context_set_http_transport(
      ctx,
      transport,
      transport_ctx,
    ));
  }

  late final _aa_context_set_http_transportPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<aa_context_t>, aa_http_fn,
              ffi.Pointer<ffi.Void>)>>('aa_context_set_http_transport');
  late final _aa_context_set_http_transport =
      _aa_context_set_http_transportPtr.asFunction<
          int Function(
              ffi.Pointer<aa_context_t>, aa_http_fn, ffi.Pointer<ffi.Void>)>();

  /// Audit F-02: register a free function paired with the paymaster
  /// middleware. Pass NULL to clear (the SDK then frees `paymaster_data` via
  /// libc free — only safe when the middleware allocated via aa_alloc or
  /// libc malloc, as the built-in aa_paymaster_zerodev does).
  aa_status aa_context_set_paymaster_free_fn(
    ffi.Pointer<aa_context_t> ctx,
    aa_paymaster_free_fn free_fn,
  ) {
    return aa_status.fromValue(_aa_context_set_paymaster_free_fn(
      ctx,
      free_fn,
    ));
  }

  late final _aa_context_set_paymaster_free_fnPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<aa_context_t>,
              aa_paymaster_free_fn)>>('aa_context_set_paymaster_free_fn');
  late final _aa_context_set_paymaster_free_fn =
      _aa_context_set_paymaster_free_fnPtr.asFunction<
          int Function(ffi.Pointer<aa_context_t>, aa_paymaster_free_fn)>();

  aa_status aa_context_set_paymaster_middleware(
    ffi.Pointer<aa_context_t> ctx,
    aa_paymaster_fn middleware,
  ) {
    return aa_status.fromValue(_aa_context_set_paymaster_middleware(
      ctx,
      middleware,
    ));
  }

  late final _aa_context_set_paymaster_middlewarePtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<aa_context_t>,
              aa_paymaster_fn)>>('aa_context_set_paymaster_middleware');
  late final _aa_context_set_paymaster_middleware =
      _aa_context_set_paymaster_middlewarePtr.asFunction<
          int Function(ffi.Pointer<aa_context_t>, aa_paymaster_fn)>();

  void aa_free(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _aa_free(
      ptr,
    );
  }

  late final _aa_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'aa_free');
  late final _aa_free =
      _aa_freePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// ZeroDev gas price middleware. Calls zd_getUserOperationGasPrice.
  aa_status aa_gas_zerodev(
    ffi.Pointer<aa_context_t> ctx,
    ffi.Pointer<aa_gas_prices_t> out,
  ) {
    return aa_status.fromValue(_aa_gas_zerodev(
      ctx,
      out,
    ));
  }

  late final _aa_gas_zerodevPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<aa_context_t>,
              ffi.Pointer<aa_gas_prices_t>)>>('aa_gas_zerodev');
  late final _aa_gas_zerodev = _aa_gas_zerodevPtr.asFunction<
      int Function(ffi.Pointer<aa_context_t>, ffi.Pointer<aa_gas_prices_t>)>();

  /// ---- Error details ----
  ffi.Pointer<ffi.Char> aa_get_last_error() {
    return _aa_get_last_error();
  }

  late final _aa_get_last_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'aa_get_last_error');
  late final _aa_get_last_error =
      _aa_get_last_errorPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// ZeroDev paymaster middleware. Calls pm_getPaymasterStubData / pm_getPaymasterData.
  aa_status aa_paymaster_zerodev(
    ffi.Pointer<aa_context_t> ctx,
    ffi.Pointer<ffi.Char> userop_json,
    int userop_json_len,
    ffi.Pointer<ffi.Char> entry_point,
    int chain_id,
    aa_pm_phase phase,
    ffi.Pointer<aa_paymaster_result_t> out,
  ) {
    return aa_status.fromValue(_aa_paymaster_zerodev(
      ctx,
      userop_json,
      userop_json_len,
      entry_point,
      chain_id,
      phase.value,
      out,
    ));
  }

  late final _aa_paymaster_zerodevPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<aa_context_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Size,
              ffi.Pointer<ffi.Char>,
              ffi.Uint64,
              ffi.UnsignedInt,
              ffi.Pointer<aa_paymaster_result_t>)>>('aa_paymaster_zerodev');
  late final _aa_paymaster_zerodev = _aa_paymaster_zerodevPtr.asFunction<
      int Function(
          ffi.Pointer<aa_context_t>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
          int,
          int,
          ffi.Pointer<aa_paymaster_result_t>)>();

  /// ---- High-level: full pipeline ----
  aa_status aa_send_userop(
    ffi.Pointer<aa_account_t> account,
    ffi.Pointer<aa_call_t> calls,
    int calls_len,
    ffi.Pointer<ffi.Uint8> hash_out,
  ) {
    return aa_status.fromValue(_aa_send_userop(
      account,
      calls,
      calls_len,
      hash_out,
    ));
  }

  late final _aa_send_useropPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<aa_account_t>,
              ffi.Pointer<aa_call_t>,
              ffi.Size,
              ffi.Pointer<ffi.Uint8>)>>('aa_send_userop');
  late final _aa_send_userop = _aa_send_useropPtr.asFunction<
      int Function(ffi.Pointer<aa_account_t>, ffi.Pointer<aa_call_t>, int,
          ffi.Pointer<ffi.Uint8>)>();

  aa_status aa_signer_custom(
    ffi.Pointer<aa_signer_vtable> vtable,
    ffi.Pointer<ffi.Void> ctx,
    ffi.Pointer<ffi.Pointer<aa_signer_t>> out,
  ) {
    return aa_status.fromValue(_aa_signer_custom(
      vtable,
      ctx,
      out,
    ));
  }

  late final _aa_signer_customPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<aa_signer_vtable>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<aa_signer_t>>)>>('aa_signer_custom');
  late final _aa_signer_custom = _aa_signer_customPtr.asFunction<
      int Function(ffi.Pointer<aa_signer_vtable>, ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Pointer<aa_signer_t>>)>();

  /// Destroy a signer handle.
  void aa_signer_destroy(
    ffi.Pointer<aa_signer_t> signer,
  ) {
    return _aa_signer_destroy(
      signer,
    );
  }

  late final _aa_signer_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<aa_signer_t>)>>(
          'aa_signer_destroy');
  late final _aa_signer_destroy = _aa_signer_destroyPtr
      .asFunction<void Function(ffi.Pointer<aa_signer_t>)>();

  /// Create a local signer with a randomly generated private key.
  aa_status aa_signer_generate(
    ffi.Pointer<ffi.Pointer<aa_signer_t>> out,
  ) {
    return aa_status.fromValue(_aa_signer_generate(
      out,
    ));
  }

  late final _aa_signer_generatePtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<ffi.Pointer<aa_signer_t>>)>>('aa_signer_generate');
  late final _aa_signer_generate = _aa_signer_generatePtr
      .asFunction<int Function(ffi.Pointer<ffi.Pointer<aa_signer_t>>)>();

  /// Create a local signer from a 32-byte private key.
  aa_status aa_signer_local(
    ffi.Pointer<ffi.Uint8> private_key,
    ffi.Pointer<ffi.Pointer<aa_signer_t>> out,
  ) {
    return aa_status.fromValue(_aa_signer_local(
      private_key,
      out,
    ));
  }

  late final _aa_signer_localPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Pointer<aa_signer_t>>)>>('aa_signer_local');
  late final _aa_signer_local = _aa_signer_localPtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Pointer<aa_signer_t>>)>();

  /// Create a JSON-RPC signer (Privy, custodial wallets, etc.).
  aa_status aa_signer_rpc(
    ffi.Pointer<ffi.Char> rpc_url,
    ffi.Pointer<ffi.Uint8> address,
    ffi.Pointer<ffi.Pointer<aa_signer_t>> out,
  ) {
    return aa_status.fromValue(_aa_signer_rpc(
      rpc_url,
      address,
      out,
    ));
  }

  late final _aa_signer_rpcPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Pointer<ffi.Pointer<aa_signer_t>>)>>('aa_signer_rpc');
  late final _aa_signer_rpc = _aa_signer_rpcPtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Pointer<aa_signer_t>>)>();

  /// Sign an EIP-7702 authorization tuple (chainId, delegation-target, EOA nonce).
  ///
  /// Works on any signer. Custom signers may implement this natively via their
  /// vtable; otherwise the SDK computes keccak256(0x05 || rlp([chainId, address,
  /// nonce])) and signs the hash with sign_hash.
  aa_status aa_signer_sign_authorization(
    ffi.Pointer<aa_signer_t> signer,
    int chain_id,
    ffi.Pointer<ffi.Uint8> address,
    int nonce,
    ffi.Pointer<aa_authorization_t> out,
  ) {
    return aa_status.fromValue(_aa_signer_sign_authorization(
      signer,
      chain_id,
      address,
      nonce,
      out,
    ));
  }

  late final _aa_signer_sign_authorizationPtr = _lookup<
          ffi.NativeFunction<
              ffi.UnsignedInt Function(
                  ffi.Pointer<aa_signer_t>,
                  ffi.Uint64,
                  ffi.Pointer<ffi.Uint8>,
                  ffi.Uint64,
                  ffi.Pointer<aa_authorization_t>)>>(
      'aa_signer_sign_authorization');
  late final _aa_signer_sign_authorization =
      _aa_signer_sign_authorizationPtr.asFunction<
          int Function(ffi.Pointer<aa_signer_t>, int, ffi.Pointer<ffi.Uint8>,
              int, ffi.Pointer<aa_authorization_t>)>();

  aa_status aa_userop_apply_gas_json(
    ffi.Pointer<aa_userop_t> op,
    ffi.Pointer<ffi.Char> gas_json,
    int gas_json_len,
  ) {
    return aa_status.fromValue(_aa_userop_apply_gas_json(
      op,
      gas_json,
      gas_json_len,
    ));
  }

  late final _aa_userop_apply_gas_jsonPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<aa_userop_t>,
              ffi.Pointer<ffi.Char>, ffi.Size)>>('aa_userop_apply_gas_json');
  late final _aa_userop_apply_gas_json =
      _aa_userop_apply_gas_jsonPtr.asFunction<
          int Function(ffi.Pointer<aa_userop_t>, ffi.Pointer<ffi.Char>, int)>();

  aa_status aa_userop_apply_paymaster_json(
    ffi.Pointer<aa_userop_t> op,
    ffi.Pointer<ffi.Char> pm_json,
    int pm_json_len,
  ) {
    return aa_status.fromValue(_aa_userop_apply_paymaster_json(
      op,
      pm_json,
      pm_json_len,
    ));
  }

  late final _aa_userop_apply_paymaster_jsonPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<aa_userop_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Size)>>('aa_userop_apply_paymaster_json');
  late final _aa_userop_apply_paymaster_json =
      _aa_userop_apply_paymaster_jsonPtr.asFunction<
          int Function(ffi.Pointer<aa_userop_t>, ffi.Pointer<ffi.Char>, int)>();

  /// ---- Low-level: step-by-step UserOp control ----
  aa_status aa_userop_build(
    ffi.Pointer<aa_account_t> account,
    ffi.Pointer<aa_call_t> calls,
    int calls_len,
    ffi.Pointer<ffi.Pointer<aa_userop_t>> out,
  ) {
    return aa_status.fromValue(_aa_userop_build(
      account,
      calls,
      calls_len,
      out,
    ));
  }

  late final _aa_userop_buildPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<aa_account_t>,
              ffi.Pointer<aa_call_t>,
              ffi.Size,
              ffi.Pointer<ffi.Pointer<aa_userop_t>>)>>('aa_userop_build');
  late final _aa_userop_build = _aa_userop_buildPtr.asFunction<
      int Function(ffi.Pointer<aa_account_t>, ffi.Pointer<aa_call_t>, int,
          ffi.Pointer<ffi.Pointer<aa_userop_t>>)>();

  aa_status aa_userop_destroy(
    ffi.Pointer<aa_userop_t> op,
  ) {
    return aa_status.fromValue(_aa_userop_destroy(
      op,
    ));
  }

  late final _aa_userop_destroyPtr = _lookup<
          ffi
          .NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<aa_userop_t>)>>(
      'aa_userop_destroy');
  late final _aa_userop_destroy = _aa_userop_destroyPtr
      .asFunction<int Function(ffi.Pointer<aa_userop_t>)>();

  aa_status aa_userop_hash(
    ffi.Pointer<aa_userop_t> op,
    ffi.Pointer<aa_account_t> account,
    ffi.Pointer<ffi.Uint8> hash_out,
  ) {
    return aa_status.fromValue(_aa_userop_hash(
      op,
      account,
      hash_out,
    ));
  }

  late final _aa_userop_hashPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<aa_userop_t>,
              ffi.Pointer<aa_account_t>,
              ffi.Pointer<ffi.Uint8>)>>('aa_userop_hash');
  late final _aa_userop_hash = _aa_userop_hashPtr.asFunction<
      int Function(ffi.Pointer<aa_userop_t>, ffi.Pointer<aa_account_t>,
          ffi.Pointer<ffi.Uint8>)>();

  aa_status aa_userop_sign(
    ffi.Pointer<aa_userop_t> op,
    ffi.Pointer<aa_account_t> account,
  ) {
    return aa_status.fromValue(_aa_userop_sign(
      op,
      account,
    ));
  }

  late final _aa_userop_signPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<aa_userop_t>,
              ffi.Pointer<aa_account_t>)>>('aa_userop_sign');
  late final _aa_userop_sign = _aa_userop_signPtr.asFunction<
      int Function(ffi.Pointer<aa_userop_t>, ffi.Pointer<aa_account_t>)>();

  aa_status aa_userop_to_json(
    ffi.Pointer<aa_userop_t> op,
    ffi.Pointer<ffi.Pointer<ffi.Char>> json_out,
    ffi.Pointer<ffi.Size> len_out,
  ) {
    return aa_status.fromValue(_aa_userop_to_json(
      op,
      json_out,
      len_out,
    ));
  }

  late final _aa_userop_to_jsonPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<aa_userop_t>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Pointer<ffi.Size>)>>('aa_userop_to_json');
  late final _aa_userop_to_json = _aa_userop_to_jsonPtr.asFunction<
      int Function(ffi.Pointer<aa_userop_t>, ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>)>();

  /// Wait for a UserOp to be included on-chain, returning the full
  /// eth_getUserOperationReceipt JSON response.
  ///
  /// Polls every poll_interval_ms, up to timeout_ms.
  /// Pass 0 for timeout_ms to use default (60 seconds).
  /// Pass 0 for poll_interval_ms to use default (2 seconds).
  ///
  /// On success, *json_out is a heap-allocated JSON string that the caller
  /// must free with aa_free(). *json_len_out is set to the string length.
  ///
  /// The JSON response follows the ERC-4337 eth_getUserOperationReceipt schema:
  /// { userOpHash, entryPoint, sender, nonce, paymaster,
  /// actualGasCost, actualGasUsed, success, logs, receipt }
  aa_status aa_wait_for_user_operation_receipt(
    ffi.Pointer<aa_account_t> account,
    ffi.Pointer<ffi.Uint8> userop_hash,
    int timeout_ms,
    int poll_interval_ms,
    ffi.Pointer<ffi.Pointer<ffi.Char>> json_out,
    ffi.Pointer<ffi.Size> json_len_out,
  ) {
    return aa_status.fromValue(_aa_wait_for_user_operation_receipt(
      account,
      userop_hash,
      timeout_ms,
      poll_interval_ms,
      json_out,
      json_len_out,
    ));
  }

  late final _aa_wait_for_user_operation_receiptPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<aa_account_t>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Uint32,
              ffi.Uint32,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Pointer<ffi.Size>)>>('aa_wait_for_user_operation_receipt');
  late final _aa_wait_for_user_operation_receipt =
      _aa_wait_for_user_operation_receiptPtr.asFunction<
          int Function(
              ffi.Pointer<aa_account_t>,
              ffi.Pointer<ffi.Uint8>,
              int,
              int,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Pointer<ffi.Size>)>();
}

final class aa_account extends ffi.Opaque {}

typedef aa_account_t = aa_account;

/// ---- EIP-7702 authorization ----
final class aa_authorization_t extends ffi.Struct {
  @ffi.Uint64()
  external int chain_id;

  @ffi.Array.multi([20])
  external ffi.Array<ffi.Uint8> address;

  @ffi.Uint64()
  external int nonce;

  @ffi.Uint8()
  external int y_parity;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> r;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> s;
}

/// ---- Call struct ----
final class aa_call extends ffi.Struct {
  @ffi.Array.multi([20])
  external ffi.Array<ffi.Uint8> target;

  /// u256, big-endian
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> value_be;

  external ffi.Pointer<ffi.Uint8> calldata;

  @ffi.Size()
  external int calldata_len;
}

typedef aa_call_t = aa_call;

final class aa_context extends ffi.Opaque {}

/// ---- Opaque handles ----
typedef aa_context_t = aa_context;

/// Gas price middleware function pointer.
/// Called by aa_send_userop to fetch current gas prices.
typedef aa_gas_price_fn
    = ffi.Pointer<ffi.NativeFunction<aa_gas_price_fnFunction>>;
typedef aa_gas_price_fnFunction = ffi.UnsignedInt Function(
    ffi.Pointer<aa_context_t> ctx, ffi.Pointer<aa_gas_prices_t> out);
typedef Dartaa_gas_price_fnFunction = aa_status Function(
    ffi.Pointer<aa_context_t> ctx, ffi.Pointer<aa_gas_prices_t> out);

/// ---- Gas price middleware ----
final class aa_gas_prices_t extends ffi.Struct {
  @ffi.Uint64()
  external int max_fee_per_gas;

  @ffi.Uint64()
  external int max_priority_fee_per_gas;

  static ffi.Pointer<aa_gas_prices_t> $allocate(
    ffi.Allocator $allocator, {
    required int max_fee_per_gas,
    required int max_priority_fee_per_gas,
  }) =>
      $allocator<aa_gas_prices_t>()
        ..ref.max_fee_per_gas = max_fee_per_gas
        ..ref.max_priority_fee_per_gas = max_priority_fee_per_gas;
}

/// Custom HTTP transport — lets host use URLSession (iOS), OkHttp, etc.
///
/// Allocator contract (audit F-02): the response buffer placed in
/// *response_out MUST be allocated via `aa_alloc` (or libc `malloc`) for the
/// SDK to free it directly. Hosts using a different allocator MUST register
/// a matching free callback via `aa_context_set_http_free_fn`. Mixing — a
/// Go/Rust/Python-runtime pointer with no free fn registered — is undefined
/// behavior; on macOS the process aborts immediately.
typedef aa_http_fn = ffi.Pointer<ffi.NativeFunction<aa_http_fnFunction>>;
typedef aa_http_fnFunction = ffi.Int Function(
    ffi.Pointer<ffi.Void> ctx,
    ffi.Pointer<ffi.Char> url,
    ffi.Pointer<ffi.Char> body,
    ffi.Size body_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_out,
    ffi.Pointer<ffi.Size> response_len_out);
typedef Dartaa_http_fnFunction = int Function(
    ffi.Pointer<ffi.Void> ctx,
    ffi.Pointer<ffi.Char> url,
    ffi.Pointer<ffi.Char> body,
    int body_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_out,
    ffi.Pointer<ffi.Size> response_len_out);

/// Optional companion to aa_http_fn. If registered, the SDK calls this to
/// release the response buffer instead of libc `free`.
typedef aa_http_free_fn
    = ffi.Pointer<ffi.NativeFunction<aa_http_free_fnFunction>>;
typedef aa_http_free_fnFunction = ffi.Void Function(ffi.Pointer<ffi.Void> ctx,
    ffi.Pointer<ffi.Uint8> response, ffi.Size response_len);
typedef Dartaa_http_free_fnFunction = void Function(ffi.Pointer<ffi.Void> ctx,
    ffi.Pointer<ffi.Uint8> response, int response_len);

/// ---- Kernel version enum ----
enum aa_kernel_version {
  AA_KERNEL_V3_3(0);

  final int value;
  const aa_kernel_version(this.value);

  static aa_kernel_version fromValue(int value) => switch (value) {
        0 => AA_KERNEL_V3_3,
        _ => throw ArgumentError('Unknown value for aa_kernel_version: $value'),
      };
}

/// Paymaster middleware function pointer.
/// Called by aa_send_userop to sponsor UserOperations.
/// Receives UserOp JSON, entry point, chain ID, and phase.
///
/// Allocator contract (audit F-02): `paymaster_data` MUST be allocated via
/// `aa_alloc` (or libc `malloc`) when the SDK is responsible for freeing.
/// If your runtime uses a different allocator (Go runtime, Rust global,
/// etc.), register a matching free callback via
/// `aa_context_set_paymaster_free_fn`. The built-in `aa_paymaster_zerodev`
/// uses libc allocation, so consumers using only it need no extra wiring.
///
/// Optional: if not set, aa_send_userop sends unsponsored (user pays gas).
typedef aa_paymaster_fn
    = ffi.Pointer<ffi.NativeFunction<aa_paymaster_fnFunction>>;
typedef aa_paymaster_fnFunction = ffi.UnsignedInt Function(
    ffi.Pointer<aa_context_t> ctx,
    ffi.Pointer<ffi.Char> userop_json,
    ffi.Size userop_json_len,
    ffi.Pointer<ffi.Char> entry_point,
    ffi.Uint64 chain_id,
    ffi.UnsignedInt phase,
    ffi.Pointer<aa_paymaster_result_t> out);
typedef Dartaa_paymaster_fnFunction = aa_status Function(
    ffi.Pointer<aa_context_t> ctx,
    ffi.Pointer<ffi.Char> userop_json,
    int userop_json_len,
    ffi.Pointer<ffi.Char> entry_point,
    int chain_id,
    aa_pm_phase phase,
    ffi.Pointer<aa_paymaster_result_t> out);

/// Optional companion to aa_paymaster_fn. If registered, the SDK calls this
/// to release `paymaster_data` instead of libc `free`. See aa_paymaster_fn
/// doc comment for the allocator contract.
typedef aa_paymaster_free_fn
    = ffi.Pointer<ffi.NativeFunction<aa_paymaster_free_fnFunction>>;
typedef aa_paymaster_free_fnFunction = ffi.Void Function(
    ffi.Pointer<aa_context_t> ctx,
    ffi.Pointer<ffi.Uint8> paymaster_data,
    ffi.Size paymaster_data_len);
typedef Dartaa_paymaster_free_fnFunction = void Function(
    ffi.Pointer<aa_context_t> ctx,
    ffi.Pointer<ffi.Uint8> paymaster_data,
    int paymaster_data_len);

final class aa_paymaster_result_t extends ffi.Struct {
  @ffi.Array.multi([20])
  external ffi.Array<ffi.Uint8> paymaster;

  @ffi.Uint64()
  external int paymaster_verification_gas_limit;

  @ffi.Uint64()
  external int paymaster_post_op_gas_limit;

  external ffi.Pointer<ffi.Uint8> paymaster_data;

  @ffi.Size()
  external int paymaster_data_len;
}

/// ---- Paymaster middleware ----
enum aa_pm_phase {
  /// Before gas estimation
  AA_PM_STUB(0),

  /// After gas estimation
  AA_PM_FINAL(1);

  final int value;
  const aa_pm_phase(this.value);

  static aa_pm_phase fromValue(int value) => switch (value) {
        0 => AA_PM_STUB,
        1 => AA_PM_FINAL,
        _ => throw ArgumentError('Unknown value for aa_pm_phase: $value'),
      };
}

final class aa_signer extends ffi.Opaque {}

typedef aa_signer_t = aa_signer;

/// Create a custom signer from a vtable of function pointers.
///
/// sign_authorization is OPTIONAL (may be NULL). When NULL, the SDK falls back
/// to computing keccak256(0x05 || rlp([chainId, address, nonce])) and calling
/// sign_hash.
///
/// NOTE: This field was appended to the struct. Consumers MUST recompile against
/// this header before linking — the ABI is NOT compatible with code that was
/// built against the older 4-field vtable (the SDK reads past the old layout).
/// C99 zero-initialization (`aa_signer_vtable v = {.sign_hash = ...};`) covers
/// this field automatically at compile time, making the change source-compatible.
final class aa_signer_vtable extends ffi.Struct {
  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Void> ctx,
              ffi.Pointer<ffi.Uint8> hash,
              ffi.Pointer<ffi.Uint8> sig_out)>> sign_hash;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Void> ctx,
              ffi.Pointer<ffi.Uint8> msg,
              ffi.Size msg_len,
              ffi.Pointer<ffi.Uint8> sig_out)>> sign_message;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Void> ctx,
              ffi.Pointer<ffi.Uint8> hash,
              ffi.Pointer<ffi.Uint8> sig_out)>> sign_typed_data_hash;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Int Function(
                  ffi.Pointer<ffi.Void> ctx, ffi.Pointer<ffi.Uint8> addr_out)>>
      get_address;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Void> ctx,
              ffi.Uint64 chain_id,
              ffi.Pointer<ffi.Uint8> address,
              ffi.Uint64 nonce,
              ffi.Pointer<aa_authorization_t> out)>> sign_authorization;

  static ffi.Pointer<aa_signer_vtable> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<
            ffi.NativeFunction<
                ffi.Int Function(
                    ffi.Pointer<ffi.Void> ctx,
                    ffi.Pointer<ffi.Uint8> hash,
                    ffi.Pointer<ffi.Uint8> sig_out)>>
        sign_hash,
    required ffi.Pointer<
            ffi.NativeFunction<
                ffi.Int Function(
                    ffi.Pointer<ffi.Void> ctx,
                    ffi.Pointer<ffi.Uint8> msg,
                    ffi.Size msg_len,
                    ffi.Pointer<ffi.Uint8> sig_out)>>
        sign_message,
    required ffi.Pointer<
            ffi.NativeFunction<
                ffi.Int Function(
                    ffi.Pointer<ffi.Void> ctx,
                    ffi.Pointer<ffi.Uint8> hash,
                    ffi.Pointer<ffi.Uint8> sig_out)>>
        sign_typed_data_hash,
    required ffi.Pointer<
            ffi.NativeFunction<
                ffi.Int Function(ffi.Pointer<ffi.Void> ctx,
                    ffi.Pointer<ffi.Uint8> addr_out)>>
        get_address,
    required ffi.Pointer<
            ffi.NativeFunction<
                ffi.Int Function(
                    ffi.Pointer<ffi.Void> ctx,
                    ffi.Uint64 chain_id,
                    ffi.Pointer<ffi.Uint8> address,
                    ffi.Uint64 nonce,
                    ffi.Pointer<aa_authorization_t> out)>>
        sign_authorization,
  }) =>
      $allocator<aa_signer_vtable>()
        ..ref.sign_hash = sign_hash
        ..ref.sign_message = sign_message
        ..ref.sign_typed_data_hash = sign_typed_data_hash
        ..ref.get_address = get_address
        ..ref.sign_authorization = sign_authorization;
}

/// ---- Status codes ----
enum aa_status {
  AA_OK(0),
  AA_NULL_OUT_PTR(1),
  AA_INVALID_URL(2),
  AA_OUT_OF_MEMORY(3),
  AA_INVALID_PRIVATE_KEY(4),
  AA_INVALID_KERNEL_VERSION(5),
  AA_NULL_CONTEXT(6),
  AA_NULL_ACCOUNT(7),
  AA_NULL_USEROP(8),
  AA_GET_ADDRESS_FAILED(9),
  AA_BUILD_USEROP_FAILED(10),
  AA_HASH_USEROP_FAILED(11),
  AA_SIGN_USEROP_FAILED(12),
  AA_SEND_USEROP_FAILED(13),
  AA_ESTIMATE_GAS_FAILED(14),
  AA_PAYMASTER_FAILED(15),
  AA_NO_CALLS(16),
  AA_INVALID_HEX(17),
  AA_APPLY_JSON_FAILED(18),
  AA_SERIALIZE_FAILED(19),
  AA_NO_GAS_MIDDLEWARE(20),
  AA_NO_PAYMASTER_MIDDLEWARE(21),
  AA_RECEIPT_TIMEOUT(22),
  AA_RECEIPT_FAILED(23),
  AA_INVALID_SIGNER(24);

  final int value;
  const aa_status(this.value);

  static aa_status fromValue(int value) => switch (value) {
        0 => AA_OK,
        1 => AA_NULL_OUT_PTR,
        2 => AA_INVALID_URL,
        3 => AA_OUT_OF_MEMORY,
        4 => AA_INVALID_PRIVATE_KEY,
        5 => AA_INVALID_KERNEL_VERSION,
        6 => AA_NULL_CONTEXT,
        7 => AA_NULL_ACCOUNT,
        8 => AA_NULL_USEROP,
        9 => AA_GET_ADDRESS_FAILED,
        10 => AA_BUILD_USEROP_FAILED,
        11 => AA_HASH_USEROP_FAILED,
        12 => AA_SIGN_USEROP_FAILED,
        13 => AA_SEND_USEROP_FAILED,
        14 => AA_ESTIMATE_GAS_FAILED,
        15 => AA_PAYMASTER_FAILED,
        16 => AA_NO_CALLS,
        17 => AA_INVALID_HEX,
        18 => AA_APPLY_JSON_FAILED,
        19 => AA_SERIALIZE_FAILED,
        20 => AA_NO_GAS_MIDDLEWARE,
        21 => AA_NO_PAYMASTER_MIDDLEWARE,
        22 => AA_RECEIPT_TIMEOUT,
        23 => AA_RECEIPT_FAILED,
        24 => AA_INVALID_SIGNER,
        _ => throw ArgumentError('Unknown value for aa_status: $value'),
      };
}

final class aa_userop extends ffi.Opaque {}

typedef aa_userop_t = aa_userop;
