include: package:lints/recommended.yaml

analyzer:
  exclude:
    - 'lib/src/ffi/aa_bindings.g.dart'
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - prefer_final_locals
    - unawaited_futures
